---
name: "CI-Testing"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["develop", "master"]

jobs:
  linters:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Lint & Code Format
        run: |
          echo 'Running Flake8' && \
          poetry run flake8 . && \
          echo 'Running Black' && \
          poetry run black --check --diff . && \
          echo 'Running Yamllint' && \
          poetry run yamllint . && \
          echo 'Running pydocstyle' && \
          poetry run pydocstyle . && \
          echo 'Running Bandit' && \
          poetry run bandit --recursive ./ --configfile .bandit.yml && \
          echo 'Running MyPy' && \
          poetry run mypy .

  test:
    name: Testing on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction

      - name: Pytest
        run: poetry run pytest

  codecov:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction

      - name: Pytest
        run: |
          poetry run pytest --cov=nornir_hier_config --cov-report=xml -vvvv

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    needs:
      - test

  publish_testpypi:
    name: "Push Package to PyPI"
    runs-on: "ubuntu-latest"
    steps:
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish package
        run: poetry publish --build -r testpypi
    needs:
      - test

  publish_pypi:
    name: "Push Package to PyPI"
    runs-on: "ubuntu-latest"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages"
        run: "pip install poetry"
      - name: "Set env"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Push to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          user: "__token__"
          password: "${{ secrets.PYPI_API_TOKEN }}"
    needs:
      - "test"
